
		baseURL = "https://www.matthartley.com"
		languageCode = "en-us"
		title = "Matt Hartley"
		theme = "aafu"

[params]
    title = "Matt Hartley"
    author = "Matt Hartley"
    description = "About Me"
    copyright = "Last update: July 10th, 2020"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Matt Hartley"
		tagline = "Community Manager"
		location = "Washington State, USA"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        		
        [[params.social.list]]
            class = "fab"
            icon = "#fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/ctsdownloads/matthartley"
            title = "GitHub"
		[[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/matthartley/"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/matthartley"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "#ai-google-scholar"
            url = "#"
            title = "Google Scholar"
		[[params.social.list]]
            class = "ai"
            icon = "#ai-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I'm the community manager for the OpenShot project. I handle the community management elements of OpenShot - Social, Reddit, end-user to developer outreach, that's me. I have worked with Linux desktops for well over a decade, my operating system experience consists of both Windows and Linux operating platforms. I've also worked as a podcast producer, co-host and technology writer. For OpenShot inquiries, email me at matt(at)openshot.org and for all other inquiries, you can reach me at matt(at)matthartley.com"

    # Experience section
    [params.experience]
        title = "Experience"
        icon = "fas fa-briefcase"

	[[params.experience.list]]
            position = "Founder and Talking Head"
            dates = "Sept 2020 - *Present*"
			link = "http://OldSchoolis.Cool"
            company = "Old School Community"
            details = "Old School serves as an escape for those wishing to remember what life was like in decades past. Here we share funny stories of our youth, take pride in doing things the “old school” way. Each post here allows us to remember memories, pop culture and TV/movies from the 1960s. 1970s, and 1980s."
        [[params.experience.list]]
            position = "Community Manager"
            dates = "May 2020 - Dec 2020"
			link = "https://www.openshot.org/"
            company = "OpenShot Studios, LLC"
            details = "I handled end user questions on social media and GitHub, community outreach. I also provide how-tos and teach others how to use the OpenShot video editor using video tutorials."
        [[params.experience.list]]
            position = "WordPress Administrator"
            dates = "June 2017 - Sept 2020"
            company = "Contract Work"
			details = "Installation, repair and overall day-to-day management of WordPress websites for contract clients. Additional tasks include backup management, hardening WordPress installations, integrating video/audio into existing WordPress sites."
		[[params.experience.list]]
            position = "Founder & Contributor"
            dates = "Aug 2015 - Jan 2020"
			link = "https://web.archive.org/web/20191226045145/https://freedompenguin.com/"
            company = "Freedom Penguin"
            details = "**(No longer own the domain, squatters are running the site as of July 2020.)** Worked closely with contributors, editors and the Freedom Penguin community. Created written and video content about Linux. Responsible for WordPress hosting and management of the website's back-end functionality, security."
		[[params.experience.list]]
            position = "Freelance Contributor"
            dates = "June 2007 - July 2018"
			link = "https://www.datamation.com/"
            company = "Datamation"
            details = "Wrote editorial articles on Linux/Open Source software for Datamation.com. Articles presented offer an in-depth topic analysis."
		[[params.experience.list]]
            position = "Community Manager / Freelance Consultant"
            dates = "Feb 2006 - Dec 2016"
			link = "https://www.earthnetworks.com/"
            company = "Earth Networks"
            details = "Built the Earth Networks Backyard Weather Community from the ground up. Moderated posts and approved member requests. Provided back-end support for the community website, also helped beta test new consumer and professional weather monitoring software. I also handled Earth Networks's Backyard Community social channels."
		[[params.experience.list]]
            position = "Founder & Tech"
            dates = "July 2003 - Aug 2008"
			company = "Computer Troubleshoot"
            details = "Managed my own PC Repair Business. Directed the business end of things while handling the technical challenges my clients faced. Tackled typical computer issues, while educating clients on how to best use their PCs."
		[[params.experience.list]]
            position = "Producer & Co-Founder"
            dates = "June 2005 - June 2007"
			company = "Weezy and The Swish"
            details = "TechTV's Laura Swisher, myself and Premiere Radio co-founder Louise Palanker created an audio podcast in the spirit of comedy called 'Weezy and The Swish.' Audio production work was handled by Matt Sigman, while I handled the website and RSS/podcasting syndication."

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

		[[params.project.list]]
            title = "Old School Community"
            description = "My most recent community management project is building a community for those who miss days gone by. Old School serves as an escape for those wishing to remember what life was like in decades past. Here we share funny stories of our youth, take pride in doing things the “old school” way. Each post here allows us to remember memories, pop culture and TV/movies from the 1960s. 1970s, and 1980s. We do virtual movie watch parties and soon, virtual board game experiences for those looking to let loose after a long week."
        
		[[params.project.list]]
            title = "OpenShot Community"
            description = "I'm the OpenShot video editor project community manager. Opportunities I face include troubleshooting issues that end users may experience. My duties include providing support and casual interaction on social media, how-to videos and providing support on Reddit/r/openshot. When I'm not providing support, I'm fielding community feedback for new features, interacting with volunteer software testers and sharing user created video projects with the rest of the community."
        [[params.project.list]]
            title = "Freedom Penguin Website"
            description = "I created and built a community around a website called Freedom Penguin. I was the talking head, while other contributors from the Linux community created articles and informational videos that desktop Linux enthusiasts enjoyed. Freedom Penguin was a huge success for a number of years."
        [[params.project.list]]
            title = "Earth Networks Backyard Weather Community"
            description = "My time at Earth Networks was spent building a community of backyard weather enthusiasts that numbered in the tens of thousands while maintaining the community website. In addition to interacting and sharing user feedback, I helped cultivate a civil ecosystem of discourse while encouraging feedback and engagement."          

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Community Building"
            skillrating = 90
        [[params.skill.list]]
            skill = "Troubleshooting"
            skillrating = 85
        [[params.skill.list]]
            skill = "Linux"
            skillrating = 75
		[[params.skill.list]]
            skill = "WordPress management"
            skillrating = 78
		[[params.skill.list]]
            skill = "Blogging"
            skillrating = 82

