
		baseURL = "https://www.matthartley.com"
		languageCode = "en-us"
		title = "Matt Hartley"
		theme = "aafu"

[params]
    title = "Matt Hartley"
    author = "Matt Hartley"
    description = "About Me"
    copyright = "Last update June 15th, 2020"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = true

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Matt Hartley"
		tagline = "Community Manager"
		location = "Washington State, USA"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        		
        [[params.social.list]]
            class = "fab"
            icon = "#fa-stack-overflow"
            url = "#"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/ctsdownloads/matthartley"
            title = "GitHub"
		[[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/matthartley/"
            title = "LinkedIn"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/matthartley"
            title = "Twitter"
		[[params.social.list]]
            class = "ai"
            icon = "#ai-google-scholar"
            url = "#"
            title = "Google Scholar"
		[[params.social.list]]
            class = "ai"
            icon = "#ai-researchgate"
            url = "#"
            title = "ResearchGate"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I currently serve as the community manager for the OpenShot project."

    # Experience section
    [params.experience]
        title = "Experience"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Community Manager"
            dates = "May 2020 - *Present*"
			link = "https://www.openshot.org/"
            company = "OpenShot Studios, LLC"
            details = "Opportunities I face include troubleshooting issues that end users may experience while sharing successes had by those who choose OpenShot to develop their video creations. My duties include providing support and casual interaction on social media, in how-to videos and providing support on Reddit/r/openshot. When I'm not providing support, I'm fielding community feedback for new features, interacting with volunteer software testers and sharing community created video projects to celebrate work our community put together using OpenShot."
        [[params.experience.list]]
            position = "WordPress Administrator"
            dates = "June 2017 - *Present*"
            company = "Contract Work"
			details = "Deploying installation, repair and overall day-to-day management of WordPress websites for contract clients. Additional tasks include backup management, hardening WordPress installations, integrating video/audio into existing WordPress sites."
		[[params.experience.list]]
            position = "Founder & Contributor"
            dates = "Aug 2015 - Jan 2020"
			link = "https://web.archive.org/web/20191226045145/https://freedompenguin.com/"
            company = "Freedom Penguin"
            details = "Worked closely with contributors, editors and the community for FreedomPenguin.com. Created written and video content about Linux. Responsible for WordPress hosting and management of the website's back-end functionality, security."
		[[params.experience.list]]
            position = "Freelance Contributor"
            dates = "June 2007 - July 2018"
			link = "https://www.datamation.com/"
            company = "Datamation"
            details = "Wrote editorial articles on Linux/Open Source software for Datamation.com. Articles presented offer an in-depth topic analysis."
		[[params.experience.list]]
            position = "Community Manager / Freelance Consultant"
            dates = "Feb 2006 - Dec 2016"
			link = "https://www.earthnetworks.com/"
            company = "Earth Networks"
            details = "Built the Earth Networks backyard weather enthusiast community from the ground up. Moderated posts and approved member requests. Provided backend support for the community website, also helped beta test new consumer and professional weather monitoring software."
		[[params.experience.list]]
            position = "Founder & Tech"
            dates = "July 2003 - Aug 2008"
			company = "Computer Troubleshoot"
            details = "Managed my own PC Repair Business. Directed the business end of things while handling the technical challenges my clients faced. Tackled client computer issues, educated clients on how to best use their PCs."
		[[params.experience.list]]
            position = "Producer & Co-Founder"
            dates = "June 2005 - June 2007"
			company = "Weezy and The Swish"
            details = "TechTV's Laura Swisher, myself and Premiere Radio co-founder Louise Palanker brainstormed and created an audio podcast in the spirit of comedy called 'Weezy and The Swish.' Audio production work was handled by Matt Sigman, while I handled the website and RSS/podcasting syndication. Post-July 2007 onward, I moved onto another project."

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

